#
# [ Database Configuration Section ]
#
spring:

  datasource:
    url: postgres://localhost:5432/postgres
    username: postgres
    password: postgres
    platform: POSTGRESQL

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  # ==============================================================
  # = Spring Security / Queries for AuthenticationManagerBuilder
  # ==============================================================
  queries:
    users-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?

server:
  port: 9095